blank_issues_enabled: false
contact_links:
  - name: QQ 2群
    url: http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=qk2lHfzjy1zxBBH4Gzpdby_D5l5BBRTy&authKey=e4gai6kHIffsLOnjR5hP6U%2BuU5JX%2B8LoU3LM%2BVmSjJCkuyBj1NqDjGtEgpUpFSV4&noverify=0&group_code=741440379
    about: 群号741440379
  - name: 作者QQ
    url: http://wpa.qq.com/msgrd?v=3&uin=3387251845&site=qq&menu=yes
    about: 添加主题作者qq